"""Deterministic constants for Stage 1 triage."""

DETERMINISTIC_VERSION = "triage-v1"

NATIVE_CHAR_DENSITY_THRESHOLD = 0.002
NATIVE_IMAGE_RATIO_MAX = 0.20

SCANNED_CHAR_COUNT_MAX = 20
SCANNED_IMAGE_RATIO_MIN = 0.60

FIGURE_HEAVY_IMAGE_RATIO_MIN = 0.45
TABLE_HEAVY_GRID_SCORE_MIN = 0.35
MULTI_COLUMN_CLUSTER_MIN = 2

LANGUAGE_CONFIDENCE_FALLBACK = 0.50

